# Question 21
# What is the expected behavior of the following snippet?
# def fun(a, b=0, c=5, d=1):
#     return a ** b ** c
# print(fun(b=2, a=2, c=3))
# It will:
# A. print 5
# B. print 64
# C. print 256
# D. print 512
# E. The code will cause a runtime exception/error