# Question 22
# What is the expected behavior of the following snippet?
# x=5
# f = lambda x: 1 + 2 print(f(x))
# It will:
# A. print 5
# B. print 8
# C. print 3
# D. The code will cause a runtime exception/error